### ISSUE TITLE
doesent work with 1.19.2

### ISSUE THREAD

**Issue by Albe8** [GirafiStudios/MineMenu#146]
Hi. im currently playing ftb essentials, journeymap, travelers backpack, travelers titles, world edit and everything works fine. When i open the mine menu i can add anything but as soon as i try to use it the client closes with -1 error ((like the version of the mod is not the same as the laucnher, which is, cause the only 1.19.2 download i can find its the 1.19 which doesent work with my version.)) Could u guys please make a 1.19.2 version that works? :D thank u very much and have a nice day. ))) The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.player.LocalPlayer.m_234156_(java.lang.String)' ------Thats the error it gives me

**Comment by GirafiStudios** [comment]
You're very much correct!
Any reason you're still on 1.19.2, rather than 1.19.3 or 1.19.4?

**Comment by tgstyle** [comment]
Can this get fixed for 1.19.2? I have this same problem but unless you can make every mod author move to 1.19.4, I am stuck on 1.19.2 for now.
